// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAU00Jz0hqjvrkf04sBzQ5V6RWBA7PKbiA',
    appId: '1:768221769660:web:81a1cdc776b47c6de745b9',
    messagingSenderId: '768221769660',
    projectId: 'sell-n-buy-rent-7ca04',
    authDomain: 'sell-n-buy-rent-7ca04.firebaseapp.com',
    databaseURL: 'https://sell-n-buy-rent-7ca04-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sell-n-buy-rent-7ca04.firebasestorage.app',
    measurementId: 'G-4VG9JRD1C1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsgVfmsqIwYGvosCKWeCnf6HpL_cR0aW4',
    appId: '1:768221769660:android:99e10b390b2160e9e745b9',
    messagingSenderId: '768221769660',
    projectId: 'sell-n-buy-rent-7ca04',
    databaseURL: 'https://sell-n-buy-rent-7ca04-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sell-n-buy-rent-7ca04.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRfh_El6Yy4bQeXwKLeXJj9rKUCZAgFRk',
    appId: '1:768221769660:ios:e099cb5d31eea38fe745b9',
    messagingSenderId: '768221769660',
    projectId: 'sell-n-buy-rent-7ca04',
    databaseURL: 'https://sell-n-buy-rent-7ca04-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sell-n-buy-rent-7ca04.firebasestorage.app',
    iosBundleId: 'com.example.sellNBuyUpdated',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRfh_El6Yy4bQeXwKLeXJj9rKUCZAgFRk',
    appId: '1:768221769660:ios:e099cb5d31eea38fe745b9',
    messagingSenderId: '768221769660',
    projectId: 'sell-n-buy-rent-7ca04',
    databaseURL: 'https://sell-n-buy-rent-7ca04-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sell-n-buy-rent-7ca04.firebasestorage.app',
    iosBundleId: 'com.example.sellNBuyUpdated',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAU00Jz0hqjvrkf04sBzQ5V6RWBA7PKbiA',
    appId: '1:768221769660:web:9e5dde217d9caf6ee745b9',
    messagingSenderId: '768221769660',
    projectId: 'sell-n-buy-rent-7ca04',
    authDomain: 'sell-n-buy-rent-7ca04.firebaseapp.com',
    databaseURL: 'https://sell-n-buy-rent-7ca04-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sell-n-buy-rent-7ca04.firebasestorage.app',
    measurementId: 'G-3V6324G7EG',
  );
}
